- job:
    name: pbr-installation-openstack-base
    timeout: 5400
    description: |
      Base job for pbr jobs that install openstack packages with current
      pbr. This ensures we don't break our ability to install openstack.
    required-projects:
      # TODO update this list with current active python projects
      - openstack/pbr
      - openstack/tripleo-ci
      - openstack/aodh
      - openstack/automaton
      - openstack/ceilometer
      - openstack/ceilometermiddleware
      - openstack/cinder
      - openstack/cliff
      - openstack/debtcollector
      - openstack/dib-utils
      - openstack/diskimage-builder
      - openstack/futurist
      - openstack/glance
      - openstack/glance_store
      - openstack/heat
      - openstack/heat-cfntools
      - openstack/heat-templates
      - openstack/horizon
      - openstack/ironic
      - openstack/ironic-lib
      - openstack/ironic-python-agent
      - openstack/keystone
      - openstack/keystoneauth
      - openstack/keystonemiddleware
      - openstack/manila
      - openstack/manila-ui
      - openstack/neutron
      - openstack/neutron-vpnaas
      - openstack/nova
      - openstack/octavia
      - openstack/os-apply-config
      - openstack/os-brick
      - openstack/os-client-config
      - openstack/os-collect-config
      - openstack/os-net-config
      - openstack/os-refresh-config
      - openstack/osc-lib
      - openstack/oslo.cache
      - openstack/oslo.concurrency
      - openstack/oslo.config
      - openstack/oslo.context
      - openstack/oslo.db
      - openstack/oslo.i18n
      - openstack/oslo.log
      - openstack/oslo.messaging
      - openstack/oslo.middleware
      - openstack/oslo.policy
      - openstack/oslo.reports
      - openstack/oslo.rootwrap
      - openstack/oslo.serialization
      - openstack/oslo.service
      - openstack/oslo.utils
      - openstack/oslo.versionedobjects
      - openstack/oslo.vmware
      - openstack/pycadf
      - openstack/python-cinderclient
      - openstack/python-glanceclient
      - openstack/python-heatclient
      - openstack/python-ironicclient
      - openstack/python-keystoneclient
      - openstack/python-manilaclient
      - openstack/python-neutronclient
      - openstack/python-novaclient
      - openstack/python-openstackclient
      - openstack/python-saharaclient
      - openstack/python-swiftclient
      - openstack/python-troveclient
      - openstack/python-zaqarclient
      - openstack/requirements
      - openstack/sahara
      - openstack/sahara-dashboard
      - openstack/stevedore
      - openstack/swift
      - openstack/taskflow
      - openstack/tempest
      - openstack/tooz
      - openstack/tripleo-heat-templates
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard
      - openstack/zaqar

- job:
    name: pbr-installation-openstack
    parent: pbr-installation-openstack-base
    pre-run: playbooks/pbr-installation-openstack/pre.yaml
    run: playbooks/pbr-installation-openstack/run.yaml
    vars:
      pbr_pip_version: ''

- job:
    name: pbr-installation-openstack-pip-dev
    description: |
      This job runs the pbr installations with pip trunk.
    parent: pbr-installation-openstack
    vars:
      pbr_pip_version: 'git+https://github.com/pypa/pip.git#egg=pip'

- job:
    name: pbr-installation-openstack-focal
    parent: pbr-installation-openstack
    nodeset: ubuntu-focal
    description: |
      Run pbr integration testing on older Ubuntu which allows us
      to test compatibility with older versions of pip and setuptools.

- project:
    templates:
      - lib-forward-testing
      - lib-forward-testing-python3
      - periodic-stable-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-cover
        - openstack-tox-py27
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-py39
        - pbr-installation-openstack
        - pbr-installation-openstack-focal
        - pbr-installation-openstack-pip-dev
        - tempest-full: &py2-tempest-overrides
            # Default to stable/train as we want to integration test PBR
            # against python2.7 and train is the last 2.7 release.
            override-checkout: stable/train
            # Provide tag specific overrides for projects that have dropped
            # train.
            required-projects:
              - name: opendev.org/openstack/placement
                override-checkout: train-eol
              - name: opendev.org/openstack/neutron
                override-checkout: train-eol
              - name: opendev.org/openstack/nova
                override-checkout: train-eol
              - name: opendev.org/openstack/glance
                override-checkout: train-eol
            vars:
              tox_envlist: smoke
    gate:
      jobs:
        - openstack-tox-pep8
        - openstack-tox-cover
        - openstack-tox-py27
        - openstack-tox-py36
        - openstack-tox-py37
        - openstack-tox-py38
        - openstack-tox-py39
        - pbr-installation-openstack
        - pbr-installation-openstack-focal
        - pbr-installation-openstack-pip-dev
        - tempest-full: *py2-tempest-overrides
    periodic:
      jobs:
        - pbr-installation-openstack
        - pbr-installation-openstack-pip-dev
        - tempest-full: *py2-tempest-overrides
