- job:
    name: pbr-installation-openstack-base
    timeout: 5400
    description: |
      Base job for pbr jobs that install openstack packages with current
      pbr. This ensures we don't break our ability to install openstack.
    required-projects:
      # TODO update this list with current active python projects
      - openstack/pbr
      - openstack/tripleo-ci
      - openstack/aodh
      - openstack/automaton
      - openstack/ceilometer
      - openstack/ceilometermiddleware
      - openstack/cinder
      - openstack/cliff
      - openstack/debtcollector
      - openstack/dib-utils
      - openstack/diskimage-builder
      - openstack/django_openstack_auth
      - openstack/futurist
      - openstack/glance
      - openstack/glance_store
      - openstack/heat
      - openstack/heat-cfntools
      - openstack/heat-templates
      - openstack/horizon
      - openstack/ironic
      - openstack/ironic-lib
      - openstack/ironic-python-agent
      - openstack/keystone
      - openstack/keystoneauth
      - openstack/keystonemiddleware
      - openstack/manila
      - openstack/manila-ui
      - openstack/neutron
      - openstack/neutron-vpnaas
      - openstack/nova
      - openstack/octavia
      - openstack/os-apply-config
      - openstack/os-brick
      - openstack/os-client-config
      - openstack/os-collect-config
      - openstack/os-net-config
      - openstack/os-refresh-config
      - openstack/osc-lib
      - openstack/oslo.cache
      - openstack/oslo.concurrency
      - openstack/oslo.config
      - openstack/oslo.context
      - openstack/oslo.db
      - openstack/oslo.i18n
      - openstack/oslo.log
      - openstack/oslo.messaging
      - openstack/oslo.middleware
      - openstack/oslo.policy
      - openstack/oslo.reports
      - openstack/oslo.rootwrap
      - openstack/oslo.serialization
      - openstack/oslo.service
      - openstack/oslo.utils
      - openstack/oslo.versionedobjects
      - openstack/oslo.vmware
      - openstack/pycadf
      - openstack/python-cinderclient
      - openstack/python-glanceclient
      - openstack/python-heatclient
      - openstack/python-ironicclient
      - openstack/python-keystoneclient
      - openstack/python-manilaclient
      - openstack/python-neutronclient
      - openstack/python-novaclient
      - openstack/python-openstackclient
      - openstack/python-saharaclient
      - openstack/python-swiftclient
      - openstack/python-troveclient
      - openstack/python-zaqarclient
      - openstack/requirements
      - openstack/sahara
      - openstack/sahara-dashboard
      - openstack/stevedore
      - openstack/swift
      - openstack/taskflow
      - openstack/tempest
      - openstack/tooz
      - openstack/tripleo-heat-templates
      - openstack/tripleo-image-elements
      - openstack/trove
      - openstack/trove-dashboard
      - openstack/zaqar

- job:
    name: pbr-installation-openstack
    parent: pbr-installation-openstack-base
    pre-run: playbooks/pbr-installation-openstack/pre.yaml
    run: playbooks/pbr-installation-openstack/run.yaml
    vars:
      pbr_pip_version: ''

- job:
    name: pbr-installation-openstack-pip-dev
    description: |
      This job runs the pbr installations with pip trunk.
    parent: pbr-installation-openstack
    vars:
      pbr_pip_version: 'git+https://github.com/pypa/pip.git#egg=pip'

- project:
    templates:
      - lib-forward-testing
      - lib-forward-testing-python3
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python3-ussuri-jobs
      - periodic-stable-jobs
      - publish-openstack-docs-pti
    check:
      jobs:
        - pbr-installation-openstack
        - pbr-installation-openstack-pip-dev
    gate:
      jobs:
        - pbr-installation-openstack
        - pbr-installation-openstack-pip-dev
    periodic:
      jobs:
        - pbr-installation-openstack
        - pbr-installation-openstack-pip-dev
